apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-sites
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: wordpress
  project: imprint
  source:
    path: wordpress
    repoURL: https://github.com/ocf/imprint-sites.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true

