services:
  wordpress:
    image: ocf-wordpress-core:latest
    restart: unless-stopped
    environment:
      DB_NAME: meow
      DB_USER: meowuser
      DB_PASSWORD: meowpassword
      DB_HOST: mariadb
    ports:
      - 8080:8080
    volumes:
      - wp-uploads:/share/wordpress/wp-content/uploads
    tmpfs:
      /tmp
    depends_on:
      mariadb:
        condition: service_healthy
        restart: true
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: meow
      MARIADB_USER: meowuser
      MARIADB_PASSWORD: meowpassword
      MARIADB_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    #tmpfs:
    #  /var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3
volumes:
  wp-uploads:
  db:
