apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wptest
  namespace: wptest
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 32Gi
  storageClassName: cephfs-nvme
